//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Assets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Desharp.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #desharp{position:absolute;z-index:9999991;right:0;bottom:0;}#desharp.invisible .bars,#desharp.invisible .win,#desharp .invisible{visibility:hidden;}#desharp.hidden .bars,#desharp.hidden .win{display:none;}#desharp .bars .item,#desharp .bars .btn,#desharp .win,#desharp .win *,.desharp-unbox-win,.desharp-unbox-win *,#desharp .desharp-screen,#desharp .desharp-screen *,.desharp-dump,.desharp-dump *{font-family:&apos;Consolas&apos;,courier new !important;font-weight:bold;}#desharp .bars{position:fixed;z-index:9999994;rig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bar_css {
            get {
                return ResourceManager.GetString("bar_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #desharp .desharp-screen,body.desharp-exception .desharp-screen{position:fixed !important;z-index:9999990;width:100%;height:100%;top:0;left:0;overflow:auto !important;background:#fff !important;}#desharp .desharp-screen.hidden{display:none;}body.desharp-exception{overflow:hidden !important;margin:0 !important;}/* exception file */.desharp-screen .file{width:auto !important;margin:0 20px 0 20px;}.desharp-screen .file .title{padding:15px 0 5px 0;}.desharp-screen .file .title b,.desharp-screen .file .title a{d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bar_exception_css {
            get {
                return ResourceManager.GetString("bar_exception_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #desharp .win .body .content{padding:0 10px 10px 10px;}.desharp-unbox-win .content{padding:10px;}#desharp .body .inset,.desharp-unbox-win .inset{background:#fdf5d0;padding:5px;margin:5px 0;display:table;width:100%;}#desharp .routing .body,.desharp-unbox-win.routing{background:#fff;}#desharp .routing tr.matched td,.desharp-unbox-win.routing tr.matched td{background:#bde678 !important;}#desharp .routing tr.ignore td,.desharp-unbox-win.routing tr.ignore td{background:#efb0a9 !important;}#desharp .win .head .ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bar_panels_css {
            get {
                return ResourceManager.GetString("bar_panels_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #desharp .win{position:absolute;z-index:9999992;right:100px;bottom:122px;-moz-border-radius:4px;-khtml-border-radius:4px;-opera-border-radius:4px;-ms-border-radius:4px;-webkit-border-radius:4px;border-radius:4px;background:rgba(255,255,255,0.9);#background:#fff;#border-width:1px;#border-style:solid;#border-top-color:#ccc;#border-left-color:#ccc;#border-bottom-color:#888;#border-right-color:#888;/*ie7-*/}@media all\0{/*ie8*/#desharp .win{#background:#fff;#border-width:1px;#border-style:solid;#border-top-colo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bar_window_css {
            get {
                return ResourceManager.GetString("bar_window_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .desharp-dump{margin:2px 5px;white-space:nowrap;}.desharp-dump:first-child{margin-top:5px;}.desharp-dump:last-child{margin-bottom:5px;}.desharp-dump,.desharp-dump *{font-size:15px;vertical-align:top;font-family:&apos;Consolas&apos;,courier new;font-weight:bold;}.desharp-dump s{display:inline-block;text-decoration:none;line-height:17px !important;}.desharp-dump div.item{white-space:nowrap;line-height:0;}#desharp .desharp-dump div.item,.desharp-unbox-win .desharp-dump div.item{height:0;width:0;overflow:hidden;}.desharp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dumps_css {
            get {
                return ResourceManager.GetString("dumps_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(a,b,c){a.map(function(d,e){c=c.replace(new RegExp(d,&apos;g&apos;),b[e])});new Function(c)()})(&apos;#%@`~&apos;.split(&apos;&apos;),&apos;function(|this|var |return|\\&apos;.split(&apos;|&apos;),&apos;window.Desharp=#I,ua,u,va,D,ia,wa,xa,Y,ja,ka,K,w,p,M,x,Z,ya,la,za,E,F,Aa,N,Ba,Ca,T,t,ma,Da,G,Ea,Fa,Ga,na,Ha,Va,Ia,A,Ja,Wa,oa,pa,Xa,Ka,y,J,Ya,aa,U,ba,qa,ca,da,H,V,O,P,La,z,Ma,L,Na,Oa,ea,Pa,W,Qa,Za,Q,ra,Ra,Sa,Ta,fa,ga,sa,Ua,C,k,v,ha,ta,m,q,R){function B(a,b,c,d,e,g,f,n){@h=%||{};h.a=R;h.u=R;&quot;string&quot;!=typeof d&amp;&amp;2==d.length?(h.ba=d[0],h.Za=d[1]):(h.ba=d,h.Z [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dumps_js {
            get {
                return ResourceManager.GetString("dumps_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;!-- &quot;&apos; --&gt;&lt;/script&gt;&lt;/style&gt;&lt;/noscript&gt;&lt;/xmp&gt;
        ///&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///&lt;meta name=&quot;robots&quot; content=&quot;noindex&quot; /&gt;
        ///&lt;title&gt;Server Error&lt;/title&gt;
        ///&lt;style&gt;
        ///#desharp{background:#fff !important;width:500px !important;margin:70px auto !important;padding:10px 20px !important;}
        ///#desharp h1,#desharp p{font-family:&apos;Arial&apos;,Helvetica,sans-serif !important;line-height:1.5em !important;background:none !important;color:#333 !important;}
        ///#desharp h1{font-weight:bold !important;font-size:47px !important;mar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string error_html {
            get {
                return ResourceManager.GetString("error_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .desharp-screen .exception .head{background:#c30000 !important;padding:20px;text-shadow:1px 1px 0 rgba(0, 0, 0, 0.4) !important;border-bottom:1px solid #ccc !important;}.desharp-screen .exception .head .type,.desharp-screen .exception .head .id,.desharp-screen .exception .head .info{color:#fff !important;font-size:14px !important;}.desharp-screen .exception .head a{display:block;font-size:28px !important;color:#fff !important;text-decoration:none !important;letter-spacing:-0.5px !important;line-height:1.15e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string exception_css {
            get {
                return ResourceManager.GetString("exception_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html,body,.record .desharp-dump,.record .desharp-dump *{font-size:12px;}html,body{font-family:&apos;Consolas&apos;,courier new;font-weight:bold;}body{margin:0;padding:5px;}.record{border-bottom:1px solid #aaa;}.record:first-child{border-top:1px solid #aaa;}.record .control{padding:3px 10px;cursor:pointer;}.record .control:hover,.record .control:focus{background:#d8d8d8;}.record .control:hover .desharp-dump .click,.record .control:focus .desharp-dump .click{border-bottom:1px solid #999 !important;}#desharp-mail .recor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logs_css {
            get {
                return ResourceManager.GetString("logs_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(a,b,c){a.map(function(d,e){c=c.replace(new RegExp(d,&apos;g&apos;),b[e])});new Function(c)()})(&apos;#%@`~&apos;.split(&apos;&apos;),&apos;function(|this|var |return|\\&apos;.split(&apos;|&apos;),&apos;window.Desharp=#t,p,qa,q,V,u,x,I,W,C,J,X,K,y,L,Y,M,Z,N,aa,ba,D,E,ra,ca,F,da,O,P,Q,wa,ea,R,z,fa,ga,ha,G,ia,sa,w,S,ja,ka,H,la,ma,A,T,na,v,m,ta,n,k,oa,U,ua,va,pa,B){function r(){@a=%||{};a.N();a.F={};a.w={}}r.B=null;r.Y=#){r.B||(r.B=new r)};r.prototype={N:#){@a=%;g.m(U,t,#b){a.X(b)})},X:#a){@b=%||{},c;c=g.a;@d=b.V(a[A]);a=d.l;@e=c(a,sa),f=c(a,p);a&amp;&amp;d.C&amp;&amp;(c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logs_js {
            get {
                return ResourceManager.GetString("logs_js", resourceCulture);
            }
        }
    }
}
