//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Assets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Desharp.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #desharp{position:absolute;z-index:9999991;right:0;bottom:0;}#desharp.invisible .bars,#desharp.invisible .win,#desharp .invisible{visibility:hidden;}#desharp.hidden .bars,#desharp.hidden .win{display:none;}#desharp .bars .item,#desharp .bars .btn,#desharp .win,#desharp .win *,.desharp-unbox-win,.desharp-unbox-win *,#desharp .screen,#desharp .screen *,.desharp-dump,.desharp-dump *{font-family:&apos;Consolas&apos;,courier new !important;font-weight:bold;}#desharp .bars{position:fixed;z-index:9999994;right:0;bottom:0;bo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bar_css {
            get {
                return ResourceManager.GetString("bar_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #desharp .screen{position:fixed;z-index:9999990;width:100%;height:100%;top:0;left:0;overflow:auto;background:#fff;}#desharp .screen.hidden{display:none;}body.desharp-screen{overflow:hidden !important;}/* exception file */#desharp .file{width:auto;margin:0 20px 0 20px;}#desharp .file .title{padding:15px 0 5px 0;}#desharp .file .title b,#desharp .file .title a{display:block;}#desharp .file .title b{color:#328adc;font-size:24px;margin-bottom:5px;}#desharp .file .title a{color:#328adc;font-size:14px;padding-bot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bar_exception_css {
            get {
                return ResourceManager.GetString("bar_exception_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #desharp .win .body .content{padding:0 10px 10px 10px;}.desharp-unbox-win .content{padding:10px;}#desharp .body .inset,.desharp-unbox-win .inset{background:#fdf5d0;padding:5px;margin:5px 0;display:table;width:100%;}#desharp .routing .body,.desharp-unbox-win.routing{background:#fff;}#desharp .routing tr.matched td,.desharp-unbox-win.routing tr.matched td{background:#bde678 !important;}#desharp .routing tr.ignore td,.desharp-unbox-win.routing tr.ignore td{background:#efb0a9 !important;}#desharp .win .head .ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bar_panels_css {
            get {
                return ResourceManager.GetString("bar_panels_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #desharp .win{position:absolute;z-index:9999992;right:100px;bottom:122px;-moz-border-radius:4px;-khtml-border-radius:4px;-opera-border-radius:4px;-ms-border-radius:4px;-webkit-border-radius:4px;border-radius:4px;background:rgba(255,255,255,0.9);#background:#fff;#border-width:1px;#border-style:solid;#border-top-color:#ccc;#border-left-color:#ccc;#border-bottom-color:#888;#border-right-color:#888;/*ie7-*/}@media all\0{/*ie8*/#desharp .win{#background:#fff;#border-width:1px;#border-style:solid;#border-top-colo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bar_window_css {
            get {
                return ResourceManager.GetString("bar_window_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .desharp-dump{margin:2px 5px;white-space:nowrap;}.desharp-dump:first-child{margin-top:5px;}.desharp-dump:last-child{margin-bottom:5px;}.desharp-dump,.desharp-dump *{font-size:15px;vertical-align:top;font-family:&apos;Consolas&apos;,courier new;font-weight:bold;}.desharp-dump s{display:inline-block;text-decoration:none;line-height:17px !important;}.desharp-dump div.item{white-space:nowrap;line-height:0;}#desharp .desharp-dump div.item,.desharp-unbox-win .desharp-dump div.item{height:0;width:0;overflow:hidden;}.desharp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dumps_css {
            get {
                return ResourceManager.GetString("dumps_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(a,b,c){a.map(function(d,e){c=c.replace(new RegExp(d,&apos;g&apos;),b[e])});new Function(c)()})(&apos;#%@`~&apos;.split(&apos;&apos;),&apos;function(|this|var |return|\\&apos;.split(&apos;|&apos;),&apos;window.Desharp=#I,sa,u,ta,D,ga,ua,va,X,ha,ia,K,w,p,M,z,Y,wa,ja,xa,E,F,ya,N,za,Aa,T,t,ka,Ba,G,Ca,Da,Ea,la,Fa,Sa,Ga,A,Ha,Ta,ma,na,Ua,Ia,x,J,Va,Z,U,aa,oa,ba,ca,H,V,O,P,Ja,y,Ka,L,La,Ma,da,Na,W,Oa,Wa,Q,pa,Pa,Qa,Ra,qa,C,k,v,ea,ra,m,q,R){function B(a,b,c,d,e,g,f,n){@h=%||{};h.a=R;h.u=R;&quot;string&quot;!=typeof d&amp;&amp;2==d.length?(h.ba=d[0],h.Za=d[1]):(h.ba=d,h.Za=d);h.g=a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dumps_js {
            get {
                return ResourceManager.GetString("dumps_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;!-- &quot;&apos; --&gt;&lt;/script&gt;&lt;/style&gt;&lt;/noscript&gt;&lt;/xmp&gt;
        ///&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///&lt;meta name=&quot;robots&quot; content=&quot;noindex&quot; /&gt;
        ///&lt;title&gt;Server Error&lt;/title&gt;
        ///&lt;style&gt;
        ///#desharp{background:#fff;width:500px;margin:70px auto;padding:10px 20px;}
        ///#desharp h1,#desharp p{font-family:&apos;Arial&apos;,Helvetica,sans-serif;line-height:1.5em;background:none;color:#333;}
        ///#desharp h1{font-weight:bold;font-size:47px;margin:.6em 0;}
        ///#desharp p{font-size:21px;margin:1.5em 0;}
        ///#desharp small{font-size:60%;color:#999;}
        ///&lt;/style&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #desharp .exception .head{background:#c30000;padding:20px;text-shadow:1px 1px 0 rgba(0, 0, 0, 0.4);border-bottom:1px solid #ccc;}#desharp .exception .head .type,#desharp .exception .head .id,#desharp .exception .head .info{color:#fff;font-size:14px;}#desharp .exception .head a{display:block;font-size:28px;color:#fff;text-decoration:none;letter-spacing:-0.5px;line-height:1.15em !important;margin:20px 0;text-align:left;}/* callstack and headers table */#desharp .calls table{display:block;border-collapse:colla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string exception_css {
            get {
                return ResourceManager.GetString("exception_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html,body,.record .desharp-dump,.record .desharp-dump *{font-size:12px;}html,body{font-family:&apos;Consolas&apos;,courier new;font-weight:bold;}body{margin:0;padding:5px;}.record{border-bottom:1px solid #aaa;}.record:first-child{border-top:1px solid #aaa;}.record .control{padding:3px 10px;cursor:pointer;}.record .control:hover,.record .control:focus{background:#d8d8d8;}.record .control:hover .desharp-dump .click,.record .control:focus .desharp-dump .click{border-bottom:1px solid #999 !important;}#desharp-mail .recor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logs_css {
            get {
                return ResourceManager.GetString("logs_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(a,b,c){a.map(function(d,e){c=c.replace(new RegExp(d,&apos;g&apos;),b[e])});new Function(c)()})(&apos;#%@`~&apos;.split(&apos;&apos;),&apos;function(|this|var |return|\\&apos;.split(&apos;|&apos;),&apos;window.Desharp=#t,p,qa,q,V,u,x,I,W,C,J,X,K,y,L,Y,M,Z,N,aa,ba,D,E,ra,ca,F,da,O,P,Q,wa,ea,R,z,fa,ga,ha,G,ia,sa,w,S,ja,ka,H,la,ma,A,T,na,v,m,ta,n,k,oa,U,ua,va,pa,B){function r(){@a=%||{};a.N();a.F={};a.w={}}r.B=null;r.Y=#){r.B||(r.B=new r)};r.prototype={N:#){@a=%;g.m(U,t,#b){a.X(b)})},X:#a){@b=%||{},c;c=g.a;@d=b.V(a[A]);a=d.l;@e=c(a,sa),f=c(a,p);a&amp;&amp;d.C&amp;&amp;(c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logs_js {
            get {
                return ResourceManager.GetString("logs_js", resourceCulture);
            }
        }
    }
}
