//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Assets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Desharp.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #desharp{position:absolute;z-index:9999991;right:0;bottom:0;}
        ///#desharp.invisible .bars,#desharp.invisible .win,#desharp .invisible{visibility:hidden;}
        ///#desharp.hidden .bars,#desharp.hidden .win{display:none;}
        ///#desharp .bars .item,#desharp .bars .btn,#desharp .win,#desharp .win *,.desharp-unbox-win,.desharp-unbox-win *,#desharp .screen,#desharp .screen *,.desharp-dump,.desharp-dump *{font-family:&apos;Consolas&apos;,courier new !important;font-weight:bold;}
        ///#desharp .bars{position:fixed;z-index:9999994;right:0;bot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bar_css {
            get {
                return ResourceManager.GetString("bar_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #desharp .screen{position:fixed;z-index:9999990;width:100%;height:100%;top:0;left:0;overflow:auto;background:#fff;}
        ///#desharp .screen.hidden{display:none;}
        ///body.desharp-screen{overflow:hidden !important;}
        ////* exception file */
        ///#desharp .file{width:auto;margin:0 20px 0 20px;}
        ///#desharp .file .title{padding:15px 0 5px 0;}
        ///#desharp .file .title b,
        ///#desharp .file .title a{display:block;}
        ///#desharp .file .title b{color:#328adc;font-size:24px;margin-bottom:5px;}
        ///#desharp .file .title a{color:#328adc;font-siz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bar_exception_css {
            get {
                return ResourceManager.GetString("bar_exception_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #desharp .win{position:absolute;z-index:9999992;right:100px;bottom:122px;-moz-border-radius:4px;-khtml-border-radius:4px;-opera-border-radius:4px;-ms-border-radius:4px;-webkit-border-radius:4px;border-radius:4px;background:rgba(255,255,255,0.9);#background:#fff;#border-width:1px;#border-style:solid;#border-top-color:#ccc;#border-left-color:#ccc;#border-bottom-color:#888;#border-right-color:#888;/*ie7-*/}
        ///@media all\0{/*ie8*/#desharp .win{#background:#fff;#border-width:1px;#border-style:solid;#border-top-co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bar_window_css {
            get {
                return ResourceManager.GetString("bar_window_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .desharp-dump,.desharp-dump *{font-size:15px;vertical-align:top;}
        ///.desharp-dump s{display:inline-block;text-decoration:none;line-height:17px !important;}
        ///.desharp-dump div.item{white-space:nowrap;line-height:0;}
        ///#desharp .desharp-dump div.item{height:0;width:0;overflow:hidden;}
        ///.desharp-dump span{display:inline-block;line-height:17px;}
        ///#desharp .desharp-dump span.click{cursor:pointer;border-bottom:1px dotted #999;padding-bottom:2px;padding-right:10px;background-color:transparent;background-repeat:no-re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dumps_css {
            get {
                return ResourceManager.GetString("dumps_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(a,b,c){a.map(function(d,e){c=c.replace(new RegExp(d,&apos;g&apos;),b[e])});new Function(c)()})(&apos;#%@`~&apos;.split(&apos;&apos;),&apos;function(|this|var |return|\\&apos;.split(&apos;|&apos;),&apos;window.Desharp=#J,sa,v,ta,D,ia,ua,va,X,ja,ka,K,y,r,M,A,Y,wa,la,xa,E,F,ya,N,za,Aa,R,u,ma,Ba,G,Ca,Da,Ea,na,Fa,Sa,Ga,B,Ha,Ta,oa,pa,Ua,Ia,w,H,Va,Z,S,T,aa,ba,ca,I,da,ea,U,Ja,z,Ka,L,La,Ma,fa,Na,V,Oa,Wa,O,qa,Pa,Qa,Ra,C,n,x,ga,ra,p,q,W){function P(a,b,c,d,e,f,k,g){@m=%||{};m.a=W;m.u=W;m.aa=d;m.f=a;m.c=b;m.g=c;m.Eb=e;m.o=f;m.K=k;m.b=g;m.da=p;m.ta=p;m.ka=p;m.ha=p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dumps_js {
            get {
                return ResourceManager.GetString("dumps_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;!-- &quot;&apos; --&gt;&lt;/script&gt;&lt;/style&gt;&lt;/noscript&gt;&lt;/xmp&gt;
        ///&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///&lt;meta name=&quot;robots&quot; content=&quot;noindex&quot; /&gt;
        ///&lt;title&gt;Server Error&lt;/title&gt;
        ///&lt;style&gt;
        ///#desharp{background:#fff;width:500px;margin:70px auto;padding:10px 20px;}
        ///#desharp h1,#desharp p{font-family:&apos;Arial&apos;,Helvetica,sans-serif;line-height:1.5em;background:none;color:#333;}
        ///#desharp h1{font-weight:bold;font-size:47px;margin:.6em 0;}
        ///#desharp p{font-size:21px;margin:1.5em 0;}
        ///#desharp small{font-size:60%;color:#999;}
        ///&lt;/style&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #desharp .exception .head{background:#c30000;padding:20px;text-shadow:1px 1px 0 rgba(0, 0, 0, 0.4);border-bottom:1px solid #ccc;}
        ///#desharp .exception .head .type,#desharp .exception .head .info{color:#fff;font-size:14px;}
        ///#desharp .exception .head a{display:block;font-size:28px;color:#fff;text-decoration:none;letter-spacing:-0.5px;line-height:1.15em !important;margin:20px 0;text-align:left;}
        ////* callstack and headers table */
        ///#desharp .calls table{display:block;border-collapse:collapse;margin:0;width:100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string exception_css {
            get {
                return ResourceManager.GetString("exception_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html,body,.record .desharp-dump,.record .desharp-dump *{font-size:12px;}
        ///html,body{font-family:&apos;Consolas&apos;,courier new;font-weight:bold;}
        ///body{margin:0;padding:5px;}
        ///
        ///.record{border-bottom:1px solid #aaa;}
        ///.record:first-child{border-top:1px solid #aaa;}
        ///.record.value{}
        ///.record.exception{}
        ///.record.opened{}
        ///.record .control{padding:3px 10px;cursor:pointer;}
        ///.record .control:hover,.record .control:focus{background:#f6f6f6;}
        ///.control .date{display:inline-block;color:#666;white-space:nowrap;padding-top:2px [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logs_css {
            get {
                return ResourceManager.GetString("logs_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(a,b,c){a.map(function(d,e){c=c.replace(new RegExp(d,&apos;g&apos;),b[e])});new Function(c)()})(&apos;#%@`~&apos;.split(&apos;&apos;),&apos;function(|this|var |return|\\&apos;.split(&apos;|&apos;),&apos;window.function t(){%.f=/MSIE [5-8]/gi.test(navigator.userAgent);v(%);%.c=0;%.a={};%.b={}}@w=null;t.prototype={};function x(a,d){@b;a===window?b=&quot;theWindow&quot;:a===document?b=&quot;theDocument&quot;:b=a.uniqueID;`&quot;{FNKEY::el_&quot;+b+&quot;::evt_click::fn_&quot;+d.toString().replace(/~s/g,&quot;&quot;)+&quot;}&quot;}function y(a){a=a.target?a.target:a.srcElement?a.srcElement:null;3==a.nodeType&amp;&amp;(a=a. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logs_js {
            get {
                return ResourceManager.GetString("logs_js", resourceCulture);
            }
        }
    }
}
