//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Assets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Desharp.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html,body{font-size:14px;font-family:&apos;Consolas&apos;,courier new;font-weight:bold;}
        ///body{border-top:1px solid #ccc;}
        ///.logger-record{display:block;padding:2px;text-decoration:none;border-bottom:1px solid #ccc;}
        ///a.logger-record-control{display:block;padding:2px;text-decoration:none;}
        ///span.logger-record-id,span.logger-record-msg{cursor:pointer;}
        ///span.logger-record-id{color:#666;}
        ///span.logger-record-msg span{color:#000;}
        ///span.logger-record-msg b{color:#328adc;}
        ///table.logger-record-dtls{display:none;}
        ///table. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DumpsCss {
            get {
                return ResourceManager.GetString("DumpsCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var Debug = (function () {
        ///	var Debug = function (unicodeIndexes) {
        ///		if (!unicodeIndexes.length) return;
        ///		var content = String.fromCharCode.apply(window, unicodeIndexes);
        ///		this.headMouseDown = [false, 0, 0];
        ///		this.resizerMouseDown = [false, 0, 0];
        ///		this.sizes = [0, 0, 100, 100];
        ///		this.cont = this.elm(&apos;div&apos;, Debug.contStyles, { id: &apos;dot-net-debug-cont&apos; });
        ///		this.head = this.elm(&apos;div&apos;, Debug.headStyles, { id: &apos;dot-net-debug-head&apos; });
        ///		this.body = this.elm(&apos;div&apos;, Debug.bodyStyles, { id: &apos;dot-n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DumpsJs {
            get {
                return ResourceManager.GetString("DumpsJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html,body{font-size:14px;font-family:&apos;Consolas&apos;,courier new;font-weight:bold;}
        ///body{border-top:1px solid #ccc;}
        ///.logger-record{display:block;padding:2px;text-decoration:none;border-bottom:1px solid #ccc;}
        ///a.logger-record-control{display:block;padding:2px;text-decoration:none;}
        ///span.logger-record-id,span.logger-record-msg{cursor:pointer;}
        ///span.logger-record-id{color:#666;}
        ///span.logger-record-msg span{color:#000;}
        ///span.logger-record-msg b{color:#328adc;}
        ///table.logger-record-dtls{display:none;}
        ///table. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LogsCss {
            get {
                return ResourceManager.GetString("LogsCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var init = function () {
        ///	var a = document.querySelectorAll(&apos;a.logger-record-control&apos;),
        ///		d = &apos;logger-record-dtls&apos;,
        ///		e = function (c) {
        ///			var o = c.querySelectorAll(&apos;span.logger-record-msg b&apos;);
        ///			c.setAttribute(&quot;href&quot;, &quot;https://www.google.com/webhp?hl=en&amp;sourceid=c-sharp-debug&amp;q=&quot; + String(o[0].innerHTML).replace(/\t\r\n/g, &quot; &quot;).replace(/ /g, &quot;+&quot;));
        ///			c.onclick = function (e) {
        ///				e = e || window.event;
        ///				if (c.parentNode.className.indexOf(d) &gt; -1) {
        ///					c.parentNode.className = c.parentNod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LogsJs {
            get {
                return ResourceManager.GetString("LogsJs", resourceCulture);
            }
        }
    }
}
